sudo: required
services:
  - docker

before_install:
  - docker build -t abhishekmadiraju/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true abhishekmadiraju/react-test npm test -- --coverage

after_success:
  - docker build -t abhishekmadiraju/multi-client ./client
  - docker build -t abhishekmadiraju/multi-nginx ./nginx
  - docker build -t abhishekmadiraju/multi-server ./server
  - docker build -t abhishekmadiraju/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push abhishekmadiraju/multi-client
  - docker push abhishekmadiraju/multi-nginx
  - docker push abhishekmadiraju/multi-server
  - docker push abhishekmadiraju/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-407150809907
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY